# Generated by Django 4.2 on 2024-03-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField()),
                ('xref', models.IntegerField()),
                ('settlement_date', models.DateField()),
                ('broker', models.CharField(max_length=255)),
                ('sub_broker', models.CharField(max_length=255, null=True)),
                ('borrower_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('total_loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('upfront', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upfront_incl_gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tier_level', models.CharField(choices=[('Tier 1', 'Tier 1'), ('Tier 2', 'Tier 2'), ('Tier 3', 'Tier 3'), ('Tier 4', 'Tier 4')], default='Tier 4', max_length=20)),
            ],
        ),
    ]
